In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,11,2) # generate a list of numbers in a range, with stepsize

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
(5,5)

(5, 5)

In [17]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.linspace(0,10,5) #generate a line with number of points

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.random.rand(5)

array([0.864364  , 0.73804802, 0.10758085, 0.60664826, 0.47205887])

In [23]:
np.random.rand(5,5)

array([[0.80332386, 0.06833965, 0.92199255, 0.91466555, 0.6295835 ],
       [0.29814649, 0.64170722, 0.598329  , 0.00684066, 0.67741968],
       [0.59779098, 0.72477658, 0.54455993, 0.54085541, 0.04125024],
       [0.19999489, 0.52911805, 0.0775089 , 0.36322112, 0.62965739],
       [0.54949185, 0.56812673, 0.22124414, 0.995339  , 0.42189189]])

In [24]:
np.random.randn(2)

array([0.36953578, 1.06321266])

In [25]:
np.random.randn(4,4)

array([[ 2.03423205, -0.95292958,  1.30509365, -0.00812574],
       [-1.42431315, -1.05605041, -0.36818812,  0.34668613],
       [-0.19863167,  0.16898727,  0.47965751, -0.44763107],
       [ 0.66239258, -0.4463665 ,  0.67382096,  1.50911734]])

In [26]:
np.random.randint(1,100,10)

array([52, 60, 31, 83, 41, 51, 38, 92, 29, 75])

In [27]:
ranarr = np.random.randint(1,100,10)

In [28]:
ranarr

array([74, 13,  2, 57,  5, 86, 74, 17, 91, 99])

In [31]:
arr = np.arange(0,25)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
arr.reshape(4,5)

ValueError: cannot reshape array of size 25 into shape (4,5)

In [35]:
arr.max()

24

In [36]:
arr.min()

0

In [37]:
arr.argmax()

24

In [38]:
arr[1,1] = 24
arr

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [39]:
arr = arr.reshape(5,5)
arr[1,1] = 24
arr[2,2] = 24
arr

array([[ 0,  1,  2,  3,  4],
       [ 5, 24,  7,  8,  9],
       [10, 11, 24, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
arr.max()

24

In [41]:
arr.argmax()

6

In [42]:
arr[1,1]

24

In [43]:
arr[6]

IndexError: index 6 is out of bounds for axis 0 with size 5

In [47]:
np.unravel_index(np.array([0,1,2,3,4,5,6,7,8,9]).argmax(), arr.shape)

(1, 4)

In [48]:
np.array([0,1,2,3,4,5,6,7,8,9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.shape(np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))


(10,)

In [53]:
arr1=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
arr1.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [54]:
arr = np.arange(0,11)

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
arr[8]

8

In [57]:
arr[1:5]

array([1, 2, 3, 4])

In [58]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [59]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [60]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [62]:
arr[0:5] = 100

In [63]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [64]:
arr_copy = arr.copy()
arr_copy


array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [66]:
arr_2d = np.array([[5,10,15], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [67]:
arr_2d[1,2]

30

In [68]:
arr_2d[1]

array([20, 25, 30])

In [69]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [70]:
#conditional selection

In [71]:
arr = np.arange(0,11)

In [72]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
bool_arr = arr > 5 #With comparison operator, this will return an arrary of Boolean values

In [75]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [76]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [77]:
arr[arr%2==0]

array([ 0,  2,  4,  6,  8, 10])

In [78]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [79]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [80]:
arr/arr

/tmp/ipykernel_94569/1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [81]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [82]:
#universal array functions

In [83]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [84]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [85]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [86]:
np.log(arr)

/tmp/ipykernel_94569/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])